name: Run integration tests

on:
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:

jobs:
  pr_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run integration tests (placeholder)
        run: echo running tests...
