name: Push versioned image to Docker Hub

on:
  release:
    types:
      - published

jobs:
  push_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get release version tag
        run: |
          echo ::set-output name=version::$(echo "${{ github.ref_name }}" | sed "s/^v//g" )
          echo ::set-output name=version_minor::$(echo "${{ github.ref_name }}" | sed -e "s/^v//g" -e "s/\.[0-9]\+$//g" )
          echo ::set-output name=version_major::$(echo "${{ github.ref_name }}" | sed -e "s/^v//g" -e "s/\.[0-9]\+$//g" -e "s/\.[0-9]\+$//g" )
        id: get_version
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: surroundaustralia/prez:${{ steps.get_version.outputs.version }},surroundaustralia/prez:${{ steps.get_version.outputs.version_minor }},surroundaustralia/prez:${{ steps.get_version.outputs.version_major }},surroundaustralia/prez:stable
